language: java
sudo: false
install: true
addons:
   sonarcloud:
      organization: "madewithpaper-github"
      token:
         secure: b4e3849336041d206b8a7b3cf17514c0436fd0e3

jdk:
   - oraclejdk8
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
   directories:
   - '$HOME/.m2/repository'
   - '$HOME/.sonar/cache'
